# Generated by Django 5.2.4 on 2025-08-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message_delete_message_to_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
