# Generated by Django 4.2.14 on 2025-08-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_about_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photoURL',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
