# Generated by Django 4.2.14 on 2025-08-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_photourl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='displayName',
            new_name='name',
        ),
    ]
