# Generated by Django 4.2.14 on 2025-08-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_displayname_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'Normal User'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='user', max_length=20),
        ),
    ]
